### ISSUE TITLE
seeking clarification on collaboration guidelines for project extension 

### ISSUE THREAD

**Issue by joseluis** [KodrAus/decstr#11]
Hi! First of all thank you this crate. I was searching for a ieee-754 decimal implementation and this is very good.

I'd like to use it as a dependency but I'd need to implement additional things like common constants, more traits like Default, Binary, also ideally PartialEq, PartialOrd... 

I was wondering if you're open to collaborations for extending the library, or do you prefer if  people would use it as a base for their own implementations? It's not clear to me from the readme.

BTW I found the `fn zero()` that calls `from(0_u8)` returns an all-zeroed byte array which is different from what would be expected, from the docs, the `from_str("0")` result and other implementations which all coincide. Is this unintended?

**Comment by KodrAus** [comment]
Hi @joseluis :wave:

Thanks for dropping by! I wrote this library because I was looking for an implementation of the bitstring encodings and couldn't find one that satisfied my needs at the time. I haven't actually gotten to using it properly yet but didn't want to let it languish so put it up on crates.io. There will absolutely be bugs and things missing besides the glaring omission of arithmetic.

I'm delighted to take PRs to this library that fill in missing bits and pieces, fix up any bugs, polish up its rough edges, and optimize or simplify anything. If you're open to hacking on it then maybe taking a fork, making any changes or additions you need for your usecase and then just opening up a big PR with them all would save you the most back-and-forth? Do feel free to open any issues with any questions you find along the way though.

If you've got some production use-case you need IEEE-754 decimals for though, you might be able to use the [`dec`](https://docs.rs/dec) library if you haven't seen it already. It's based on `libdecimal`, which is IEEE-754 compatible and widely used. Its internal format is a bitstring too, but its stored in `u32`s instead of `u8`s, so is endianness dependent.

> common constants, more traits like Default, Binary

Those sound like they'd be great additions!

> also ideally PartialEq, PartialOrd

I'd love to support this, but may be a little more tricky, since we don't currently do any normalization or have a `reduce` routine we don't have a way to tell whether `1.1` is equal to `1.10`. I think we could add one though.

>  I found the fn zero() that calls from(0_u8) returns an all-zeroed byte array

Hmm, that just doesn't seem right. It _should_ at least have an exponent of `1`. It's also a bit odd for it to differ from `from_str("0")`, since it internally formats that integer to a string using `itoa` and then converts that into a decimal using `from_str`. So they should be exactly the same. There must be something strange going on there.

**Comment by joseluis** [comment]
Hi @KodrAus! thanks very much for your comprehensive response and warm welcome.

> I'm delighted to take PRs to this library that fill in missing bits and pieces, fix up any bugs, polish up its rough edges, and optimize or simplify anything.

good to know! I just sent a PR that fixes the low hanging fruit of lint warnings and a copuple missing derives. I will add some basic constants in a later one, and will think about addressing more complicated things after...

> If you've got some production use-case you need IEEE-754 decimals for though, you might be able to use the [`dec`](https://docs.rs/dec) library if you haven't seen it already.

I saw it before and used it briefly but I discarded depending on it because I found the lib code in the gcc repo and realized it was GPL licensed. After looking at it again more carefully it seems that it actually has a [GPL+exception](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=28002) [license](https://github.com/raitechnology/libdecnumber/blob/master/COPYING.RUNTIME) which if I'm not mistakeng would allow being used in a non GPL licensed rust project without the library itself having to be GPL.



>> I found the fn zero() that calls from(0_u8) returns an all-zeroed byte array

> Hmm, that just doesn't seem right.

Hmmm. You're right. Now I can't reproduce it. I may have broken something temporarily when I was tinkering with the source that day...

**Comment by KodrAus** [comment]
> a [GPL+exception](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=28002) [license](https://github.com/raitechnology/libdecnumber/blob/master/COPYING.RUNTIME)

Ah that's the exception that allows you to dynamically but not statically link the library in proprietary software, right? We've got `dec` as a dev dependency here, just to have a known quantity to test against.

When looking at that different encoding of zero values, I did notice that `Bitstring::from(0f64)` is actually different from the others. We use `ryu` to convert binary floats to decimals and faithfully encode it. I think it encodes `0` as `0.0`, so we end up with a different value. I was thinking of fixing that so we special-case `0f64` as `0`. What do you think?

**Comment by joseluis** [comment]
I'm personally all for being as internally consistent as possible, and making breaking changes as soon as possible when is still easy. So :+1: from me.
